apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.operatorNamespace}}
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.watchedNamespaces}}
  labels:
    istio-injection: disabled
    topology.istio.io/network: network-{{.Values.istioOperator.clusterName}}
---
