apiVersion: v1
data:
  ca-cert.pem: {{.Values.ca_cert}} 
  ca-key.pem: {{.Values.ca_key}}
  cert-chain.pem: {{.Values.cert_chain}}
  root-cert.pem: {{.Values.root_cert}}
kind: Secret
metadata:
  name: cacerts
  namespace: {{.Values.watchedNamespaces}}
type: Opaque
---
{{- range .Values.clusters }}
apiVersion: v1
kind: Secret
data:
  {{.name}}: {{.kubeconfig}}
metadata:
  annotations:
    networking.istio.io/cluster: {{.name}}
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-{{.name}}
  namespace: {{ .namespace | default "istio-system" }}
type: Opaque
---
{{- end }}
